apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: nginx-ingress-controller-pub
  namespace: ingress-nginx 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-pub
      app.kubernetes.io/instance: ingress-nginx-pub
      app.kubernetes.io/component: controller-pub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx-pub
        app.kubernetes.io/instance: ingress-nginx-pub
        app.kubernetes.io/component: controller-pub
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      hostNetwork: true
      containers:
        - name: nginx-ingress-controller
          image: cnych/ingress-nginx-controller:v1.0.4 
          args:
            - /nginx-ingress-controller
            - --ingress-class=nginx-pub
            - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-2.11.1
    app.kubernetes.io/name: ingress-nginx-pub
    app.kubernetes.io/instance: ingress-nginx-pub
    app.kubernetes.io/version: 0.34.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller-pub
  annotations:
    service.cloud.tencent.com/local-svc-weighted-balance: "true"
    service.kubernetes.io/local-svc-only-bind-node-with-pod: "true"
    service.kubernetes.io/tke-existed-lbid: lb-bf5vyikp 
  name: ingress-nginx-controller-pub
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx-pub
    app.kubernetes.io/instance: ingress-nginx-pub
    app.kubernetes.io/component: controller-pub
